- hosts: localhost
  connection: local
  
  tasks:
  - name: Create & Start Container
    docker_container:
      name: myweb
      image: "yhs0728/mywebapp:{{ lookup('env','BUILD_NUMBER') }}"
      state: started
      ports:
      - "8888:8080"